import './globals.css'
// import {Inter, Poppins, Roboto} from 'next/font/google'
import {Poppins} from 'next/font/google'
import UIProvider from "@/providers/NextUIProvider";
import Header from "@/components/Header";

// const inter = Inter({subsets: ['latin']})
const poppins = Poppins({
    weight: ['400', '500', '600', '700'],
    // styles: ['regular', 'italic'],
    styles: ['normal'],
    subsets: ['latin']
})

// const roboto = Roboto({
//     weight: ['300', '400', '500', '700'],
//     styles: ['regular', 'italic'],
//     subsets: ['latin']
// })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={poppins.className}>
        <UIProvider>
            <Header/>
            {children}
        </UIProvider>
        </body>
        </html>
    )
}
